index_name:
data_type: LongmemEval  # Dataset type: "LongmemEval" or "LOCOMO"
data_root: src/dataset/longmemeval
dataset_name: LongmemEval
working_dir: results/locomo/group_3/visualizations
################################# Embedding #################################
embedding:
  api_type: "hf"
  api_key: ""
  model: "BAAI/bge-m3"
  cache_dir: "D:\\LiCoMemory\\llm_cache"
  dimensions: 1024
  max_token_size: 8192
  embed_batch_size: 128
  embedding_func_max_async: 10
#################################### LLM ####################################
llm:
  api_type: "openai"
  model: 'meta-llama/llama-3.1-8b-instruct'
  base_url: "https://openrouter.ai/api/v1"
  api_key: ""

  max_token: 8192
  temperature: 0.0
  enable_concurrent: True
  max_concurrent: 8
  timeout: 600

query_llm:
  api_type: "openai"
  base_url: "https://openrouter.ai/api/v1"
  model: 'meta-llama/llama-3.1-70b-instruct'
  api_key: ""
  max_token: 131072
  temperature: 0.2
  timeout: 600
################################### Chunk ###################################
chunk:
  chunk_token_size: 1200
  chunk_overlap_token_size: 100
  token_model: your/model
  dialogue_input: True
################################# Dialogue #################################
dialog:
  enable_turn_pairing: True
  include_session_metadata: True
  validate_dialog_format: True
################################# Graph #################################
graph:
  graph_type: dynamic_memory
  force: True
  add: False
  entity_merge_threshold: 0.85
  relationship_merge_threshold: 1
################################# Retriever #################################
retriever:
  top_k: 5
  top_k_triples: 15
  top_chunks: 15
  enable_summary: True
  top_summary: 2
  enable_visual: True
  top_visual: 15
  enable_full: True
  enable_sessiontime: True
  enable_CogniRank: True
  summary_weight: 0.25
  rerank_k: 0.1

################################# Evaluation #################################
evaluation:
  enable_llm_eval: True
  eval_model: 'meta-llama/llama-3.1-70b-instruct'
  eval_temperature: 0.0
  eval_max_tokens: 10